config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  devise_for :teachers, :skip => [:passwords, :confirmations, :omniauth_callbacks, :unlocks], controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'
  }

  resources :teachers, only: [] do
    get "time-clock" => "teachers#time_clock"
  end

  resources :clock_events, only: [:create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_event.rb
class ClockEvent < ApplicationRecord
  belongs_to :event_type
  belongs_to :teacher

  validate :created_at_validation, on: :update

  private

  # New created_at value will only be valid if:
  # - It has the right datetime format
  # - It's not before or equal the clock event that happened before it  (in case it exists)
  # - It's not equal or after the clock event that happened after it (in case it exists)
  # - It's not after Time now in EDT
  def created_at_validation
    if self.created_at.nil?
      message = "Invalid datetime format. Expected: dd/mm/yyyy - hh:mm:ss AM/PM."
      errors.add(:base, message)
      return
    end

    new_created_time = self.created_at.strftime("%d/%m/%Y - %I:%M:%S %p")

    previous_event = teacher.clock_events.where("id < ?", self.id).last
    if previous_event.present? && new_created_time <= previous_event.created_at.strftime("%d/%m/%Y - %I:%M:%S %p")
      message = "You clocked " + previous_event.event_type.name + " previously at " + previous_event.created_at.strftime("%d/%m/%Y - %I:%M:%S %p") + "."
      message += " Please choose a different clock " + self.event_type.name + " time."

      errors.add(:base, message)
      return
    end

    next_event = teacher.clock_events.where("id > ?", self.id).first
    if next_event.present? && new_created_time >= next_event.created_at.strftime("%d/%m/%Y - %I:%M:%S %p")
      message = "You already clocked " + next_event.event_type.name + " at " + next_event.created_at.strftime("%d/%m/%Y - %I:%M:%S %p") + "."
      message += " Please choose a different clock " + self.event_type.name + " time."

      errors.add(:base, message)
      return
    end

    time_now = Time.now.in_time_zone("Eastern Time (US & Canada)").strftime("%d/%m/%Y - %I:%M:%S %p")
    if new_created_time > time_now
      message = "Clock event cannot be updated to a time in the future."
      errors.add(:base, message)
      return
    end
  end

end

app/models/event_type.rb
class EventType < ApplicationRecord
  enum name: { in: 1, out: 2 }

  # There is no point in keeping the clock_events if the event types are deleted
  has_many :clock_events, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :rememberable

  # It only makes sense for clock events to exist when they are associated to a Teacher  
  has_many :clock_events, dependent: :destroy

  validates_presence_of :name

  validates :email, 
            presence: true,
            uniqueness: true

  validates :password,
            length: { minimum: 6 },
            presence: true, on: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    current_teacher ? teacher_time_clock_path(current_teacher) : root_path
  end

  def validate_teacher
    unless teacher_signed_in?
      flash.now[:error] = "Sign in to continue"
      redirect_to root_path unless teacher_signed_in?
    end
  end
  
end

app/controllers/clock_events_controller.rb
class ClockEventsController < ApplicationController
  before_action :validate_teacher
  before_action :set_clock_event, except:[:create] 

  def create
    # Check if there are any clock events and sets the new event type to the opposite of the last clock event type
    new_event_type = current_teacher.clock_events.empty? || current_teacher.clock_events.last.event_type.out? ? EventType.in : EventType.out

    clock_event = ClockEvent.new(event_type_id: new_event_type.first.id, teacher_id: current_teacher.id)
    clock_event.save

    redirect_to teacher_time_clock_path(current_teacher)
  end

  def edit
  end
  
  def update
    if @clock_event.update(clock_event_update_params)
      flash[:success] = "Time Clock Event updated"
      redirect_to teacher_time_clock_path(current_teacher)
    else
      flash.now[:error] = @clock_event.errors.full_messages.first
      render 'edit'
    end
  end

  def destroy
    if @clock_event.destroy
      flash[:success] = "Time Clock Event deleted"
    else
      flash.now[:error] = @clock_event.errors.full_messages.first
    end
    
    redirect_to teacher_time_clock_path(current_teacher)
  end

  private

  def set_clock_event
    @clock_event = ClockEvent.find(params[:id])
  end

  def clock_event_update_params
    params.require(:clock_event).permit(:created_at)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

end

app/controllers/teachers/registrations_controller.rb
# frozen_string_literal: true

class Teachers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    attributes = [:name, :email, :password]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    attributes = [:name, :email]
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    current_teacher ? teacher_time_clock_path(current_teacher) : root_path
  end

  def after_update_path_for(resource)
    current_teacher ? teacher_time_clock_path(current_teacher) : root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :validate_teacher

  def time_clock
    respond_to do |format|
      format.html
      format.json { render json: ClockEventsDatatable.new(view_context, { current_teacher: current_teacher }) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(page_title)
    content_for :page_title, page_title
  end
  
  def page_description(page_description)
    content_for :meta_description, page_description
  end

  def show_toast_error(message)
    javascript_tag("M.toast({html: '#{message}', displayLength: 8000})") unless message.blank?
  end

end

app/views/clock_events/edit.html.erb
<% page_title "Edit Clock Event | TeacherTimeClock" %>

<div class="container row">
  <div class="col s12 m6 offset-m3 l6 offset-l3 form-card">
    <div class="col s12">
      <h4>Edit Clock Event</h4></br>
    </div>
    <div class="col s12">
      <%= form_for @clock_event do |f| %>
        <div class="col s12 form-field">
          <%= f.label :name, "Datetime" %>
          <%= f.text_field :created_at, id: "datetime-field", value: @clock_event.created_at.present? ? @clock_event.created_at.strftime("%d/%m/%Y - %I:%M:%S %p") : "", autocomplete: "off" %>
        </div>
        <div class="col s12">
          <%= f.submit "Update", id: "submit-data", class: "col s12 l8 offset-l2 btn btn-default btn-blue" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<% page_title "What would you like to do today? | TeacherTimeClock" %>

<div class="container row">
  <div class="col s12">
    <div class="col s12 center home-title">
      <h4>What would you like to do today?</h4>
    </div>
    <div class="col s10 offset-s1 m8 offset-m2 l8 offset-l2 center">
      <div class="col s12 m6 l6">
        <%= link_to new_teacher_registration_path do %>
          <div class="home-card">
            <div class="card-icon">
              <%= image_tag "new-teacher.svg", alt: "Freepik Flaticon Admin" %>
            </div>
            <p>Sign up</p>
          </div>
        <% end %>
      </div>
      <div class="col s12 m6 l6">
        <%= link_to new_teacher_session_path do %>
          <div class="home-card">
            <div class="card-icon">
              <%= image_tag "time-clock.svg", alt: "Freepik Flaticon Teacher" %>
            </div>
            <p>Sign in</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar">
  <nav class="white" role="navigation">
    <%= image_tag "logo.png", alt: "Logo", class: "logo left" %>
    <ul class="right">
      <% unless (controller_name == "teachers" && action_name == "time_clock") %>
        <li><%= link_to "Time Clock", teacher_time_clock_path(current_teacher), class: "navbar-item" %></li>
      <% end %>
      <% unless (controller_name == "registrations" && action_name == "edit") %>
        <li><%= link_to "Profile", edit_teacher_registration_path, class: "navbar-item" %></li>
      <% end %>
      <li><%= link_to "Sign out", destroy_teacher_session_path, method: :delete, class: "btn-ghost" %></li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Arthur Sousa">
    <meta http-equiv="Content-Language" content="en-ca">
    <meta name="theme-color" content="#34b9c6"/>

    <% if yield(:page_title).blank? %>
      <title>Keep track of teachers clock-in and clock-out times | TeacherTimeClock</title>
    <% else %>
      <title><%= yield(:page_title) %></title>
    <% end %>
    <% if yield(:meta_description).blank? %>
      <meta name="description" content="The perfect platform to keep track of teachers clock-in and clock-out times">
    <% else %>
      <meta name="description" content='<%= yield(:meta_description) %>'>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_teacher %>
      <%= render "layouts/navbar" %>
    <% end %>

    <% flash.each do |type, message| %>
      <%= show_toast_error(message) %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_devise_error_messages.html.erb
<% if resource.errors.any? %>
  <%= show_toast_error(resource.errors.full_messages.first) %>
<% end %>

app/views/teachers/time_clock.html.erb
<% page_title "Clock Events List | TeacherTimeClock" %>

<div class="container row">
  <div class="col s10 offset-s1 time-clock-datatable-card">
    <div class="col s12 m10 l10" >
      <h4><%= current_teacher.name %> - Time Clock</h4>
    </div>
    <% if current_teacher.clock_events.empty? || current_teacher.clock_events.last.event_type.out? %>
      <%= link_to "Clock-in", clock_events_path, method: :post, class: "col s6 m2 l2 btn btn-default btn-green right" %>
    <% else %>
      <%= link_to "Clock-out", clock_events_path, method: :post, class: "col s6 m2 l2 btn btn-default btn-red right" %>
    <% end %>
    <table id="clock-events-datatable" data-source="<%= teacher_time_clock_path(format: :json) %>" cellspacing="0" width="100%" class="striped">
      <thead>
        <tr>
          <th>datetime</th>
          <th>type</th>
          <th>actions</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>datetime</th>
          <th>type</th>
          <th>actions</th>
        </tr>
      </tfoot>
      <tbody>
      </tbody>
    </table>
  </div>
</div>